/**
 * FAR FACE ATTENDANCE PRO - Google Apps Script API
 *
 * IMPORTANT:
 * 1. Paste this entire file into Extensions > Apps Script.
 * 2. Deploy > New deployment > Web app.
 * 3. Execute as: Me
 * 4. Who has access: Anyone
 * 5. Use the /exec URL in the HTML Settings.
 *
 * This version uses JSONP for browser requests so the HTML hosted on
 * another domain (e.g. fulkumari.com.np) does not get blocked by CORS.
 */

const EMPLOYEE_SHEET = 'Employees';
const ATTENDANCE_SHEET = 'Attendance';

function doGet(e) {
  try {
    const p = (e && e.parameter) ? e.parameter : {};
    const action = p.action || '';
    let result;

    if (action === 'employees') {
      result = { success: true, employees: getEmployees() };
    } else if (action === 'saveEmployee') {
      const data = parsePayload(p.data);
      result = saveEmployee(data);
    } else if (action === 'attendance') {
      const data = parsePayload(p.data);
      result = saveAttendance(data);
    } else if (action === 'deleteEmployee') {
      const data = parsePayload(p.data);
      result = deleteEmployee(data.id);
    } else {
      result = {
        success: true,
        message: 'FAR Face Attendance Pro API is working.',
        actions: ['employees', 'saveEmployee', 'attendance', 'deleteEmployee']
      };
    }

    return output(result, p.callback || '');
  } catch (err) {
    return output({ success: false, error: String(err) }, e && e.parameter ? e.parameter.callback : '');
  }
}

function doPost(e) {
  try {
    const data = e && e.postData && e.postData.contents
      ? JSON.parse(e.postData.contents)
      : {};
    const action = data.action || '';
    let result;

    if (action === 'employee' || action === 'registerEmployee' || action === 'saveEmployee') {
      result = saveEmployee(data.data || data);
    } else if (action === 'attendance') {
      result = saveAttendance(data);
    } else if (action === 'deleteEmployee') {
      result = deleteEmployee((data.data || data).id);
    } else {
      result = { success: false, error: 'Unknown action: ' + action };
    }

    return output(result, '');
  } catch (err) {
    return output({ success: false, error: String(err) }, '');
  }
}

function parsePayload(value) {
  if (!value) return {};
  try {
    return JSON.parse(value);
  } catch (err) {
    throw new Error('Invalid request data: ' + err.message);
  }
}

function output(data, callback) {
  const json = JSON.stringify(data);
  if (callback) {
    // Callback is generated by the HTML itself; restrict it to a safe JS identifier.
    const safe = String(callback).replace(/[^a-zA-Z0-9_$]/g, '');
    return ContentService
      .createTextOutput(safe + '(' + json + ');')
      .setMimeType(ContentService.MimeType.JAVASCRIPT);
  }
  return ContentService
    .createTextOutput(json)
    .setMimeType(ContentService.MimeType.JSON);
}

function saveEmployee(data) {
  const sheet = getEmployeeSheet();
  const id = String(data.id || '').trim();

  if (!id) return { success: false, error: 'Employee ID is required.' };

  const row = [
    id,
    String(data.name || '').trim(),
    String(data.trade || '').trim(),
    String(data.company || '').trim(),
    String(data.department || '').trim(),
    String(data.nationality || '').trim(),
    String(data.phone || '').trim(),
    String(data.site || '').trim(),
    String(data.joiningDate || '').trim(),
    String(data.photo || data.photoUrl || '').trim(),
    String(data.registeredAt || new Date().toISOString())
  ];

  const lastRow = sheet.getLastRow();

  // Update if Employee ID already exists; otherwise append.
  if (lastRow >= 2) {
    const ids = sheet.getRange(2, 1, lastRow - 1, 1).getDisplayValues();
    for (let i = 0; i < ids.length; i++) {
      if (String(ids[i][0]).trim().toLowerCase() === id.toLowerCase()) {
        const targetRow = i + 2;
        sheet.getRange(targetRow, 1, 1, row.length).setValues([row]);
        return { success: true, action: 'updated', row: targetRow, employee: employeeObject(row) };
      }
    }
  }

  sheet.appendRow(row);
  return { success: true, action: 'created', row: sheet.getLastRow(), employee: employeeObject(row) };
}

function getEmployees() {
  const sheet = getEmployeeSheet();
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return [];

  const values = sheet.getRange(2, 1, lastRow - 1, 11).getValues();
  return values
    .filter(r => String(r[0] || '').trim() !== '')
    .map(employeeObject);
}

function employeeObject(row) {
  return {
    id: String(row[0] || ''),
    name: String(row[1] || ''),
    trade: String(row[2] || ''),
    company: String(row[3] || ''),
    department: String(row[4] || ''),
    nationality: String(row[5] || ''),
    phone: String(row[6] || ''),
    site: String(row[7] || ''),
    joiningDate: formatDateValue(row[8]),
    photo: String(row[9] || ''),
    registeredAt: String(row[10] || '')
  };
}

function saveAttendance(data) {
  const sheet = getAttendanceSheet();
  const row = [
    String(data.date || ''),
    String(data.time || ''),
    String(data.id || ''),
    String(data.name || ''),
    String(data.status || ''),
    String(data.photo || ''),
    String(data.trade || ''),
    String(data.company || ''),
    String(data.department || ''),
    String(data.nationality || ''),
    String(data.phone || ''),
    String(data.site || ''),
    String(data.joiningDate || ''),
    new Date()
  ];
  sheet.appendRow(row);
  return { success: true, row: sheet.getLastRow(), message: 'Attendance saved successfully.' };
}

function deleteEmployee(id) {
  const sheet = getEmployeeSheet();
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return { success: false, error: 'No employees found.' };

  const ids = sheet.getRange(2, 1, lastRow - 1, 1).getDisplayValues();
  for (let i = 0; i < ids.length; i++) {
    if (String(ids[i][0]).trim().toLowerCase() === String(id || '').trim().toLowerCase()) {
      sheet.deleteRow(i + 2);
      return { success: true, message: 'Employee deleted successfully.' };
    }
  }
  return { success: false, error: 'Employee ID not found.' };
}

function getEmployeeSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(EMPLOYEE_SHEET);
  if (!sheet) sheet = ss.insertSheet(EMPLOYEE_SHEET);

  const headers = [
    'Employee ID', 'Full Name', 'Trade', 'Company', 'Department',
    'Nationality', 'Phone / WhatsApp', 'Site / Project', 'Joining Date',
    'Photo URL', 'Registered At'
  ];

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    sheet.setFrozenRows(1);
  }
  return sheet;
}

function getAttendanceSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(ATTENDANCE_SHEET);
  if (!sheet) sheet = ss.insertSheet(ATTENDANCE_SHEET);

  const headers = [
    'Date', 'Time', 'Employee ID', 'Name', 'Status', 'Photo URL', 'Trade',
    'Company', 'Department', 'Nationality', 'Phone', 'Site', 'Joining Date', 'Saved At'
  ];

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    sheet.setFrozenRows(1);
  }
  return sheet;
}

function formatDateValue(value) {
  if (!value) return '';
  if (Object.prototype.toString.call(value) === '[object Date]') {
    return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  return String(value);
}
